### ISSUE TITLE
invenio 3.3 and KVSessions

### ISSUE THREAD

**Issue by rerowep** [inveniosoftware/invenio-accounts#326]
If I try to install invenio 3.3.0 I get following error:

1. We have to install `flask_kvsession` or
2. we have to import `KVSessionExtension` from `flask_kvsession_invenio`?

Build web assets: collect
Traceback (most recent call last):
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/bin/invenio", line 11, in <module>
    sys.exit(cli())
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/flask/cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/flask/cli.py", line 523, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/invenio_oauth2server/__init__.py", line 117, in <module>
    from .decorators import require_api_auth, require_oauth_scopes  # noqa isort:skip
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/invenio_oauth2server/decorators.py", line 19, in <module>
    from .provider import oauth2
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/invenio_oauth2server/provider.py", line 21, in <module>
    from .models import Client, Token
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/invenio_oauth2server/models.py", line 17, in <module>
    from invenio_accounts.models import User
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/invenio_accounts/__init__.py", line 38, in <module>
    from .ext import InvenioAccounts, InvenioAccountsREST, InvenioAccountsUI
  File "/Users/wep/devel/virtualenvs/rero-ebooks-MevsRTH6-py3.6/lib/python3.6/site-packages/invenio_accounts/ext.py", line 18, in <module>
    from flask_kvsession import KVSessionExtension
ImportError: cannot import name 'KVSessionExtension'

**Comment by ppanero** [comment]
Hi @rerowep since `flask-kvsessions` is unmaintained, Invenio now uses its own fork of it: https://pypi.org/project/Flask-KVSession-Invenio/

Which is the one that comes with invenio-accounts v1.3.0.

Was this error produced in a clean cookiecutted instance? Or during migration? Could you `pip freeze` and send the output?
